$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: msmarco-minilm-deployment-6
endpoint_name: rerankeramlws-endpt
model:
  path: ./model/
code_configuration:
  code: ./scoring/
  scoring_script: score_msmarco_aml.py
environment:
  name: msmarco-env-6
  build: 
    path: ./environment-msmarco/
instance_type: STANDARD_D4AS_V4
instance_count: 1
request_settings:
    request_timeout_ms: 120000